jump-dev/DiffOpt.jl

src/diff_model.jl
src/utils.jl
test/diff_model.jl
test/runtests.jl

edit backward method. add more tests

---

Project.toml
src/DiffOpt.jl
src/MOI_wrapper.jl
src/utils.jl
test/MOI_wrapper.jl

Support PSD constraints

---

src/DiffOpt.jl
src/MOI_wrapper.jl
src/gen_random_problem.jl
test/MOI_wrapper.jl

Minor formatting

---

Project.toml
src/DiffOpt.jl
src/MOI_wrapper.jl
test/runtests.jl
test/solver_interface.jl

This PR removes optimizers from the direct dependencies as they shouldn't be needed, and includes the examples in the test to make sure they stay up to date

simplify project test

---

src/utils.jl
test/solver_interface.jl

Fixes the issue caused by last commit on MatrixOptInteface

Fix CSR type parameter

---

test/MOI_wrapper.jl

It was failing if you don't run the tests from the `test` folder

Allow running tests from anywhere

---

Project.toml
test/runtests.jl
test/singular_exception.jl

This test confirms that https://github.com/jump-dev/DiffOpt.jl/issues/65 is solved

singular exception issue

---

examples/unit_example.jl
src/MOI_wrapper.jl
test/runtests.jl

Adding a real-world example based on unit commitment.
In the case of an LP, the system is not invertible, I added a fallback to LSQR in case Q = 0

unit test example, conditional LSQR

---

src/diff_opt.jl
src/quadratic_diff.jl
test/conic_backward.jl

remove todos

---

src/DiffOpt.jl
src/quadratic_diff.jl
src/utils.jl

Closes https://github.com/jump-dev/DiffOpt.jl/issues/117
Closes https://github.com/jump-dev/DiffOpt.jl/issues/116
Closes https://github.com/jump-dev/DiffOpt.jl/issues/115

Fix and speed up quadratic objective conversion to sparse array format

---

src/diff_opt.jl
test/jump.jl
test/moi_wrapper.jl
test/singular_exception.jl
test/utils.jl

What we set and get is like the tangent on the ConstraintFunction while in the QP context, the constant is the set constant so we need to multiply by -1

Flip sign of constant of [ForwardIn|BackardOut]Constraint

---

docs/src/chainrules_unit.md

Ping @oxinabox, see if this is ok for Invenia to be mentioned here

mention support from Invenia

---

.github/workflows/ci.yml

remove nightly from main CI

---

src/DiffOpt.jl
src/conic_diff.jl
src/diff_opt.jl
src/moi_wrapper.jl
src/quadratic_diff.jl
test/moi_wrapper.jl
test/singular_exception.jl

First step of https://github.com/jump-dev/DiffOpt.jl/issues/167

Refactor with QPDiff and ConicDiff

---

src/conic_diff.jl
src/diff_opt.jl
src/moi_wrapper.jl
src/quadratic_diff.jl
src/utils.jl

See https://github.com/jump-dev/DiffOpt.jl/issues/167

Handle index mapping in Optimizer

---

docs/src/examples/custom-relu.jl
docs/src/examples/matrix-inversion-manual.jl
src/DiffOpt.jl
src/conic_diff.jl
src/diff_opt.jl
src/moi_wrapper.jl
src/quadratic_diff.jl
src/utils.jl
test/moi_wrapper.jl
test/singular_exception.jl

Resolve #176.
Extended from #177.
I tried to make the ReLU example clear.

Make the ReLU example clear

---

src/utils.jl

Follows the reordering of MOI.ScalarQuadraticFunction done in MOI v0.10

Reorder fields of MatrixScalarQuadratic

---

docs/src/examples/custom-relu.jl
docs/src/examples/sensitivity-analysis-ridge.jl

The text and computations were not clear

sensitivity reg

---

src/moi_wrapper.jl
test/solver_interface.jl

Closes https://github.com/jump-dev/DiffOpt.jl/issues/171

error when invalid status

---

src/moi_wrapper.jl
test/moi_wrapper.jl

solver version

---

test/jump.jl

This was broken by https://github.com/jump-dev/JuMP.jl/pull/3237

Don't access vector with []

---

test/jump.jl

Enable show test

---

.github/workflows/ci.yml

Also checks if the failure of https://github.com/jump-dev/DiffOpt.jl/pull/253 is due to the changes of the PR or not

map_indices for IndexMappedFunction

---

docs/src/examples/matrix-inversion-manual.jl

Corrected "sentivity" to  "sensitivity"

Update (typo) matrix-inversion-manual.jl

---

Project.toml

https://github.com/jump-dev/DiffOpt.jl/compare/v0.4.2...master

Prep for v0.4.3
