jump-dev/DiffOpt.jl

Project.toml
README.md
examples/solve-LP.jl
examples/solve-QP.jl
src/DiffOpt.jl
src/MOI_wrapper.jl
src/utils.jl
test/MOI_wrapper.jl

In backward_conic, `dQ` is materialized only for a matrix-vector product, it is eliminated from the pass.
There should also be a way to avoid materializing `Q`, and ultimately reasoning on the sparse construction of the problem and not its explicit matrix form

matrix-less dQ

---

src/MOI_wrapper.jl
src/utils.jl
test/MOI_wrapper.jl

https://github.com/jump-dev/MatrixOptInterface.jl/pull/22 just broke DiffOpt. This PR fixes this and also use the `convert` function added in https://github.com/jump-dev/MatrixOptInterface.jl/pull/21.

Replace CSRtoCSC by convert

---

src/MOI_wrapper.jl
src/utils.jl
test/MOI_wrapper.jl
test/runtests.jl

Handle GreaterThan constraints

---

Project.toml
src/MOI_wrapper.jl
src/utils.jl
test/jump.jl
test/runtests.jl

this copies the examples and tests from MOI to JuMP.
Most examples worked out of the box, this adds a quick fix to #82 
The conic examples are broken, with unsupported constraints, not sure why exactly (`@test_broken` added)

add JuMP tests

---

src/MOI_wrapper.jl

Wanted to emulate something like this example: https://github.com/cvxgrp/cvxpylayers/blob/master/examples/torch/tutorial.ipynb
Made some small fixes
Here's the demo: https://github.com/be-apt/jump-gsoc-2020/blob/master/sensitivity-analysis-ridge.ipynb

bug fixes in QP backend

---

Project.toml
docs/Project.toml
docs/src/index.md
examples/chainrules.jl
test/runtests.jl

Copying the unit commitment example with ChainRules.
We depend on ChainRulesCore through SetDistances, so I added it as a dependency

added ChainRules examples with forward and backward

---

docs/src/sensitivity-analysis-svm.md
docs/src/solve-conic-1.md
docs/src/usage.md
examples/chainrules.jl
examples/sensitivity-SVM.jl
examples/unit_example.jl
src/diff_opt.jl
src/jump_moi_overloads.jl
src/utils.jl
test/conic_backward.jl
test/jump.jl
test/moi_wrapper.jl
test/qp_forward.jl
test/singular_exception.jl

As detailed in https://github.com/jump-dev/DiffOpt.jl/issues/114, it would be better to have subtype of `MOI.AbstractModelAttribute`.
Having the type of the function in the attribute is needed to have a type-stable getter similarly to `MOI.ObjectiveFunction`. Probably it's not so critical this time so we can remove it (which is done in the second commit), it's mostly used in `MOI.ObjectiveFunction` for supports so that we can compute the objective bridge graph but we are probably not going to create bridges for ForwardInObjective.

ForwardIn{...Objective} -> ForwardInObjective

---

docs/src/chainrules_unit.md
docs/src/usage.md
examples/chainrules.jl
examples/unit_example.jl
src/diff_opt.jl
src/jump_moi_overloads.jl
src/quadratic_diff.jl
test/conic_backward.jl
test/jump.jl
test/moi_wrapper.jl
test/singular_exception.jl
test/utils.jl

By converting the test "Differentiating MOI examples 1" to `qp_test`, the test was failing and I was able to fix it by doing the changes suggested in https://github.com/jump-dev/DiffOpt.jl/issues/124 and https://github.com/jump-dev/DiffOpt.jl/issues/127.
So I'm quite confident on the changes on these lines.
Closes https://github.com/jump-dev/DiffOpt.jl/issues/124
Closes https://github.com/jump-dev/DiffOpt.jl/issues/127

BackwardOut -> BackwardOutConstraint

---

src/diff_opt.jl
test/jump.jl
test/utils.jl

When the user enters a `GreatherThan` constraint for a QP, it is flipped under the hood and then we consider it as a `LessThan` constraint.
However, we don't flip the function given as `ForwardInConstraint` and `BackwardOutConstraint` which is quite unexpected if the user is not award that we flip the function.
To make this transparent, this does the flipping for `ForwardInConstraint` and `BackwardOutConstraint` as well.

Fix ForwardIn and BackwardOut sign for GreaterThan in QP

---

src/diff_opt.jl
src/quadratic_diff.jl

One design decision here would be: do we want to have this as type parameter of `Optimizer` or as a field ? The advantage of a field is that it can be set with optimizer attributes and change at will while even if it may not make much sense to change it once a few constraints have already been passed and bridges have been chosen in view of the program class. But a user may want to change the class, empty and copy again, that would make sense.
Let me know what you think

Allow setting explicit problem class

---

src/diff_opt.jl
src/moi_wrapper.jl
src/quadratic_diff.jl
test/moi_wrapper.jl
test/utils.jl

Update to MOI v0.10 and JuMP v0.22

---

docs/src/chainrules_unit.md
docs/src/examples/sensitivity-analysis-svm.jl
examples/chainrules.jl
src/jump_moi_overloads.jl

Closes https://github.com/jump-dev/DiffOpt.jl/issues/152

Fix getting ForwardOutVariablePrimal with JuMP v0.22

---

docs/src/examples/custom-relu.jl
docs/src/examples/matrix-inversion-manual.jl

I've followed some tutorials, and especially in comparison between manual QP differentiation and using DiffOpt,
I thought it would be better to add some explanation why `0.0 * index(x[1])` is used and what `-1.0` stands for `cause it's confusing considering the value of `h = -1.0`.

Add explanation and fix typo in some tutorials

---

src/conic_diff.jl
src/diff_opt.jl
src/quadratic_diff.jl

This PR simply refactors QPDiff by moving code around, without actually moving to MatrixOfConstraints yet. This is to avoid polluting the diff of the next PR with these code movements.
See https://github.com/jump-dev/DiffOpt.jl/issues/167

Refactor QPDiff

---

docs/src/examples/autotuning-ridge.jl
docs/src/examples/chainrules_unit.jl
docs/src/examples/sensitivity-analysis-ridge.jl
docs/src/usage.md
src/deprecated.jl
src/diff_opt.jl
src/jump_moi_overloads.jl
src/moi_wrapper.jl
test/moi_wrapper.jl
test/utils.jl

ForwardObjective Function

---

src/ConicProgram/ConicProgram.jl
src/diff_opt.jl
test/utils.jl

This PR throws the Conic diff through all the QP tests we have with no quadratic parts, this already caught one bug that is fixed in this PR

Fix conic objective reverse diff

---

docs/src/index.md

While most of the docs just refer to "conic programs", the note at the front specifically says only second-order and semidefinite programming is supported. this adds a small mention that the exponential cone is also supported.

mention that exponential cone also works in docs

---

docs/src/manual.md

Correcting typo "acutal" to "actual"

Typo "acutal" to "actual"

---

src/utils.jl

x-ref https://github.com/jump-dev/MathOptInterface.jl/pull/2603

Implement MOI.Utilities.scalar_type for (Matrix|Sparse)VectorAffineFunction

---

src/bridges.jl
test/jump.jl

@andrewrosemberg Can you check if this fixes your issue ?
Closes https://github.com/jump-dev/DiffOpt.jl/issues/285

Pass attributes through Objective.FunctionConversionBridge

---

src/moi_wrapper.jl
test/jump_wrapper.jl

Weirdly enough, it works after the first commit but fails once I remove the outer cache.
I think this is because POI first adds a quadratic constraint and then modifies it. Apparently it's not complaining if you have two layers of caches ?

Fix diff_optimizer with no bridge
